"""initial migration

Revision ID: 63888f9f6826
Revises: 
Create Date: 2025-04-05 07:05:05.592100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63888f9f6826'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_channels_discord_id'), 'discord_channels', ['discord_id'], unique=True)
    op.create_index(op.f('ix_discord_channels_id'), 'discord_channels', ['id'], unique=False)
    op.create_table('discord_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_users_discord_id'), 'discord_users', ['discord_id'], unique=True)
    op.create_index(op.f('ix_discord_users_id'), 'discord_users', ['id'], unique=False)
    op.create_table('discord_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['discord_channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['discord_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_messages_discord_id'), 'discord_messages', ['discord_id'], unique=True)
    op.create_index(op.f('ix_discord_messages_id'), 'discord_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discord_messages_id'), table_name='discord_messages')
    op.drop_index(op.f('ix_discord_messages_discord_id'), table_name='discord_messages')
    op.drop_table('discord_messages')
    op.drop_index(op.f('ix_discord_users_id'), table_name='discord_users')
    op.drop_index(op.f('ix_discord_users_discord_id'), table_name='discord_users')
    op.drop_table('discord_users')
    op.drop_index(op.f('ix_discord_channels_id'), table_name='discord_channels')
    op.drop_index(op.f('ix_discord_channels_discord_id'), table_name='discord_channels')
    op.drop_table('discord_channels')
    # ### end Alembic commands ###
