"""add sentiment analysis fields

Revision ID: 7b6b8136e7e2
Revises: 63888f9f6826
Create Date: 2025-04-05 07:14:07.328877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6b8136e7e2'
down_revision: Union[str, None] = '63888f9f6826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discord_messages', sa.Column('protocol_name', sa.String(), nullable=True))
    op.add_column('discord_messages', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('discord_messages', sa.Column('technical_indicators', sa.Text(), nullable=True))
    op.add_column('discord_messages', sa.Column('risk_assessment', sa.String(), nullable=True))
    op.add_column('discord_messages', sa.Column('community_consensus', sa.Float(), nullable=True))
    op.alter_column('discord_messages', 'sentiment_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discord_messages', 'sentiment_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('discord_messages', 'community_consensus')
    op.drop_column('discord_messages', 'risk_assessment')
    op.drop_column('discord_messages', 'technical_indicators')
    op.drop_column('discord_messages', 'confidence')
    op.drop_column('discord_messages', 'protocol_name')
    # ### end Alembic commands ###
